### ISSUE TITLE
Issue regarding Section 310-writing-and-formatting-javascript

### ISSUE THREAD

**Issue by Sean-BREI** [BarkleyREI/Front-End-Coding-Standards#19]
## Article that needs changed

Formatting the language statements and patterns should follow these basics:
...

## Proposed change

- For named functions, do not insert a space character between the function name and the parentheses.
- For anonymous functions, do insert a space character between the function keyword and the parentheses. It’s a function definition; it’s not a function invocation. A space character helps to identify, and communicate, the difference between the use of functions.

## Justification for proposal

Clear, concise syntax.

**Comment by nessthehero** [comment]
Are you just adding these line items to the list below that heading, or are you replacing the heading?

**Comment by nessthehero** [comment]
@Sean-BREI Look at the referenced commit and see if that's correct.

**Comment by Sean-BREI** [comment]
I'm just adding those items to the list. No specific order.
